server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootAPI
    username: postgres
    password: postgres  # Ensure you provide the correct password or remove if not needed
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: RestAPI
